# Generated by Django 5.2.8 on 2025-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
