# Generated by Django 5.2.8 on 2025-11-18 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0002_grievance_category_grievance_sentiment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='summary',
        ),
        migrations.AddField(
            model_name='grievance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
