# Generated by Django 5.2.8 on 2025-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0006_remove_grievance_assigned_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='other_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
