# Generated by Django 5.2.8 on 2025-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0007_grievance_other_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolution_images/'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/'),
        ),
    ]
