# Generated by Django 5.2.8 on 2025-11-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0009_grievanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='grievance_api.department'),
        ),
    ]
