# Generated by Django 5.2.8 on 2025-11-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0010_category_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='department',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='department',
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='grievance_api.department')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='grievance_api.subdepartment'),
        ),
    ]
