# Generated by Django 5.2.8 on 2025-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0012_category_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_images/'),
        ),
    ]
