# Generated by Django 5.2.8 on 2025-11-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0013_grievance_location_alter_grievance_resolution_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='grievance_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grievance_api.grievance')),
            ],
        ),
    ]
