# Generated by Django 5.2.8 on 2025-12-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0015_department_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grievance_api.department'),
        ),
    ]
