# Generated by Django 5.2.9 on 2025-12-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0016_grievance_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='grievance_image',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_images/'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolution_images/'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
