# Generated by Django 5.2.9 on 2025-12-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0017_grievance_due_date_grievance_grievance_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Pending Approval', 'Pending Approval'), ('In Progress', 'In Progress'), ('Policy Decision', 'Policy Decision'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
