# Generated by Django 5.2.9 on 2026-01-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0018_alter_grievance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sla_days',
            field=models.PositiveIntegerField(default=7, help_text='SLA in days'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
