# Generated by Django 5.2.9 on 2026-01-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_api', '0019_department_sla_days_alter_grievance_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grievance_api.department'),
        ),
    ]
